spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: postgres
    password: example
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    open-in-view: true